# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T07:35:03+00:00

from __future__ import annotations

from enum import Enum


class Delivered(Enum):
    bool_True = True
    bool_False = False
    int_0 = 0
    int_1 = 1
